[versions]
kotlin = "2.2.21"
ksp = "2.2.21-2.0.4"
kover = "0.9.4"

ktor = "3.3.3"
spring-boot = "3.5.9"
axon = "4.12.2"
exposed = "1.0.0-rc-4"
mysql = "9.5.0"
flyway = "11.20.0"
h2 = "2.4.240"
kotlin-logging = "3.0.5"
logback = "1.5.23"
slf4j = "2.0.17"
arrow = "2.2.1.1"
koin  = "4.1.1"
koin-annotations = "2.3.1"
kord-core = "0.17.0"
ulid-kotlin = "1.5.0"
kotlinx-serialization = "1.9.0"

kotest = "6.0.4"
kotest-assertions-arrow = "2.0.0"
database-rider = "1.44.0"
db-setup-kotlin = "2.1.0"
assertj-db = "3.0.1"
mockk = "1.14.7"
testcontainers = "2.0.3"

[libraries]
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty" }
ktor-server-config-yaml = { module = "io.ktor:ktor-server-config-yaml" }
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json" }
ktor-client-core = { module = "io.ktor:ktor-client-core" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging" }
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-data-jdbc = { module = "org.springframework.boot:spring-boot-starter-data-jdbc" }
spring-kafka = { module = "org.springframework.kafka:spring-kafka" }
axon-bom = { module = "org.axonframework:axon-bom", version.ref = "axon" }
axon-spring-boot-starter = { module = "org.axonframework:axon-spring-boot-starter" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
mysql-connector-j = { module = "com.mysql:mysql-connector-j", version.ref = "mysql" }
flyway-mysql-spring = { module = "org.flywaydb:flyway-mysql" }
flyway-mysql = { module = "org.flywaydb:flyway-mysql", version.ref = "flyway" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
kotlin-logging = { module = "io.github.microutils:kotlin-logging-jvm", version.ref = "kotlin-logging" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotations" }
koin-ksp-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-annotations" }
kord-core = { module = "dev.kord:kord-core", version.ref = "kord-core" }
ulid-kotlin = { module = "com.aallam.ulid:ulid-kotlin", version.ref = "ulid-kotlin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }

kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-extensions-ktor = { module = "io.kotest:kotest-assertions-ktor", version.ref = "kotest" }
kotest-extensions-spring = { module = "io.kotest:kotest-extensions-spring", version.ref = "kotest" }
kotest-extensions-koin = { module = "io.kotest:kotest-extensions-koin", version.ref = "kotest" }
kotest-extensions-wiremock = { module = "io.kotest:kotest-extensions-wiremock", version.ref = "kotest" }
kotest-extensions-testcontainers = { module = "io.kotest:kotest-extensions-testcontainers", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-arrow = { module = "io.kotest.extensions:kotest-assertions-arrow", version.ref = "kotest-assertions-arrow" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers" }
spring-kafka-test = { module = "org.springframework.kafka:spring-kafka-test" }
koin-test = { module = "io.insert-koin:koin-test" }
database-rider-core = { module = "com.github.database-rider:rider-core", version.ref = "database-rider" }
db-setup-kotlin = { module = "com.ninja-squad:DbSetup-kotlin", version.ref = "db-setup-kotlin" }
assertj-db = { module = "org.assertj:assertj-db", version.ref = "assertj-db" }
testcontainers-mysql = { module = "org.testcontainers:testcontainers-mysql", version.ref = "testcontainers" }
testcontainers-kafka = { module = "org.testcontainers:kafka" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
awaitility-kotlin = { module = "org.awaitility:awaitility-kotlin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
