ktor:
  application:
    modules:
      - org.contourgara.ExpensesApiApplicationKt.module
  deployment:
    port: 8080

application:
  datasource:
    url: ${EXPENSES_API_DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  ulid-sequencer:
    base-url: ${ULID_SEQUENCER_BASE_URL}
