name: CI Pipeline

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/CODEOWNERS'
      - '.gitignore'
      - 'LICENSE.md'
      - 'README.md'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - discord-bot
          - finance-core
          - ulid-sequencer
          - expenses-api
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: mise install
        uses: jdx/mise-action@v3
      - name: Run unit test
        run: ./gradlew clean ${{ matrix.module }}:test

  front-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Run install dependencies
        working-directory: ./expenses-api/frontend
        run: npm ci
      - name: Run unit test
        working-directory: ./expenses-api/frontend
        run: npm run test
